apiVersion: abbyy/v1
kind: Project
metadata:
  name: test
  version: '0.0.1'
spec:
  params:
    appId: 'test'
  charts:
  - name: platform-upgrade
    values: values.yaml
    namespace: 'rtest'
    version: '0.1.17'
    upgrade: true
  - name: testmg
    values: values.yaml
    namespace: 'rtest'
    version: '0.1.20'
  - name: testmg2
    values: values.yaml
    namespace: 'rtest'
    version: '0.1.1006'
